default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  url: <%= Rails.application.credentials[:postgres_database][:development_url] %>
test:
  <<: *default
  url: <%= Rails.application.credentials[:postgres_database][:test_url]%>
production:
  <<: *default
  url: <%= Rails.application.credentials[:postgres_database][:production_url] %>
